[package]
name = "agent-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
agent-model.path = "../agent-model"
agent-tools.path = "../agent-tools"
agent-types.path = "../agent-types"
futures-core.workspace = true
futures-util.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
serde_json.workspace = true
