// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ChangeOwnPasswordData, ChangeOwnPasswordErrors, ChangeOwnPasswordResponses, CreateUserData, CreateUserErrors, CreateUserResponses, GetCenterInfoData, GetCenterInfoErrors, GetCenterInfoResponses, GetCurrentIdentityData, GetCurrentIdentityErrors, GetCurrentIdentityResponses, ListManagementAuditData, ListManagementAuditErrors, ListManagementAuditResponses, ListUsersData, ListUsersErrors, ListUsersResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, ResetUserPasswordData, ResetUserPasswordErrors, ResetUserPasswordResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * 查询中心软件与协议兼容信息
 */
export const getCenterInfo = <ThrowOnError extends boolean = false>(options?: Options<GetCenterInfoData, ThrowOnError>): RequestResult<GetCenterInfoResponses, GetCenterInfoErrors, ThrowOnError> => (options?.client ?? client).get<GetCenterInfoResponses, GetCenterInfoErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/info',
    ...options
});

/**
 * 统一登录，返回内存 Token 和关联 LLM key；无 Cookie 操作
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 查询本人和中心身份，不重复返回凭据
 */
export const getCurrentIdentity = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentIdentityData, ThrowOnError>): RequestResult<GetCurrentIdentityResponses, GetCurrentIdentityErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentIdentityResponses, GetCurrentIdentityErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * 仅废弃当前 Token 和关联 key；缺失/无效/重复退出均成功；请求体为 {}
 */
export const logout = <ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 验证原密码并修改本人密码，撤销本人全部 Token；不是管理重置
 */
export const changeOwnPassword = <ThrowOnError extends boolean = false>(options: Options<ChangeOwnPasswordData, ThrowOnError>): RequestResult<ChangeOwnPasswordResponses, ChangeOwnPasswordErrors, ThrowOnError> => (options.client ?? client).post<ChangeOwnPasswordResponses, ChangeOwnPasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 管理员查询用户，按创建时间/ID 升序分页
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users',
    ...options
});

/**
 * 创建普通用户或管理员，不允许传入超级管理员标记
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 编辑显示名称、角色或启用状态，至少一项；不允许改账号/超级管理员标记
 *
 * 带超级管理员标记的用户禁止停用或降权；角色/启用状态实际改变后撤销目标全部 Token。相同值不重复写入或审计。
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> => (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 管理员为任意用户重置密码（包括自己和超级管理员），不校验原密码；撤销目标全部 Token
 */
export const resetUserPassword = <ThrowOnError extends boolean = false>(options: Options<ResetUserPasswordData, ThrowOnError>): RequestResult<ResetUserPasswordResponses, ResetUserPasswordErrors, ThrowOnError> => (options.client ?? client).post<ResetUserPasswordResponses, ResetUserPasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 管理员只读审计查询，按时间/ID 倒序分页，不返回秘密
 */
export const listManagementAudit = <ThrowOnError extends boolean = false>(options?: Options<ListManagementAuditData, ThrowOnError>): RequestResult<ListManagementAuditResponses, ListManagementAuditErrors, ThrowOnError> => (options?.client ?? client).get<ListManagementAuditResponses, ListManagementAuditErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/audit',
    ...options
});
