// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type CenterInfo = {
    /**
     * Center 软件版本，与 Runtime 独立发布
     */
    software_version: string;
    /**
     * 当前企业协议版本
     */
    protocol_version: number;
    /**
     * 最低兼容企业协议版本
     */
    min_protocol_version: number;
};

export type CenterErrorDetail = {
    /**
     * 稳定原因码
     */
    code: string;
    /**
     * 脱敏错误说明
     */
    message: string;
    /**
     * 服务端生成的请求关联标识
     */
    request_id: string;
};

export type CenterErrorResponse = {
    error: CenterErrorDetail;
};

export type LoginRequest = {
    /**
     * 3—64 位 ASCII 账号，trim 后转小写
     */
    username: string;
};

export type IdentityUser = {
    id: number;
    username: string;
    display_name: string;
    role: 'user' | 'admin';
    is_super_admin: boolean;
    enabled: boolean;
};

export type LoginResponse = {
    center_id: string;
    user: IdentityUser;
    /**
     * 用于 Bearer 身份认证；仅内存保存，退出、撤销或中心重启后失效
     */
    token: string;
    /**
     * 仅供后续 LLM 代理使用，随本次 token 一起撤销；不用于身份 API
     */
    llm_key: string;
};

export type IdentityResponse = {
    center_id: string;
    user: IdentityUser;
};

export type PasswordRequest = {
    old_password: string;
    /**
     * 至少 6 位，包含英文字母和数字；不裁剪空白，最多 512 UTF-8 字节
     */
    new_password: string;
};

export type UserRecord = {
    id: number;
    username: string;
    display_name: string;
    role: 'user' | 'admin';
    is_super_admin: boolean;
    enabled: boolean;
    created_at: string;
    updated_at: string;
};

export type UserPage = {
    items: Array<UserRecord>;
    total: number;
    limit: number;
    offset: number;
};

export type CreateUserRequest = {
    /**
     * trim 并转小写后 3—64 位 ASCII 字母/数字及 ._-
     */
    username: string;
    display_name: string;
    role: 'user' | 'admin';
    enabled: boolean;
};

export type UpdateUserRequest = {
    display_name?: string;
    role?: 'user' | 'admin';
    enabled?: boolean;
};

export type ResetPasswordRequest = {
    /**
     * 至少 6 位，包含英文字母和数字；最多 512 UTF-8 字节；不收原密码，目标可为自己或超级管理员
     */
    new_password: string;
};

export type AuditUserFields = {
    display_name?: string;
    role?: 'user' | 'admin';
    enabled?: boolean;
};

export type AuditDetails = {
    before?: AuditUserFields;
    after?: AuditUserFields;
};

export type AuditRecord = {
    id: number;
    occurred_at: string;
    actor_user_id: number | null;
    target_user_id: number | null;
    /**
     * 关联操作者的登录用户名；未认证或关联用户不存在时为空
     */
    actor_username: string | null;
    /**
     * 关联目标用户的登录用户名；无目标或关联用户不存在时为空
     */
    target_username: string | null;
    action: string;
    success: boolean;
    reason_code: string | null;
    request_id: string;
    details: AuditDetails;
};

export type AuditPage = {
    items: Array<AuditRecord>;
    total: number;
    limit: number;
    offset: number;
};

export type LoginRequestWritable = {
    /**
     * 3—64 位 ASCII 账号，trim 后转小写
     */
    username: string;
    password: string;
};

export type CreateUserRequestWritable = {
    /**
     * trim 并转小写后 3—64 位 ASCII 字母/数字及 ._-
     */
    username: string;
    display_name: string;
    role: 'user' | 'admin';
    enabled: boolean;
    /**
     * 至少 6 位，包含英文字母和数字；最多 512 UTF-8 字节
     */
    password: string;
};

export type GetCenterInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/info';
};

export type GetCenterInfoErrors = {
    /**
     * 请求失败，返回脱敏原因码与请求标识
     */
    default: CenterErrorResponse;
};

export type GetCenterInfoError = GetCenterInfoErrors[keyof GetCenterInfoErrors];

export type GetCenterInfoResponses = {
    200: CenterInfo;
};

export type GetCenterInfoResponse = GetCenterInfoResponses[keyof GetCenterInfoResponses];

export type LoginData = {
    body: LoginRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * 400 输入无效；401 身份失败；403 来源/权限拒绝；409 状态变化；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type GetCurrentIdentityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentIdentityErrors = {
    /**
     * 400 输入无效；401 身份失败；403 来源/权限拒绝；409 状态变化；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type GetCurrentIdentityError = GetCurrentIdentityErrors[keyof GetCurrentIdentityErrors];

export type GetCurrentIdentityResponses = {
    200: IdentityResponse;
};

export type GetCurrentIdentityResponse = GetCurrentIdentityResponses[keyof GetCurrentIdentityResponses];

export type LogoutData = {
    body: {
        [key: string]: never;
    };
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * 400 输入无效；401 身份失败；403 来源/权限拒绝；409 状态变化；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ChangeOwnPasswordData = {
    body: PasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/password';
};

export type ChangeOwnPasswordErrors = {
    /**
     * 400 输入无效；401 身份失败；403 来源/权限拒绝；409 状态变化；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type ChangeOwnPasswordError = ChangeOwnPasswordErrors[keyof ChangeOwnPasswordErrors];

export type ChangeOwnPasswordResponses = {
    204: void;
};

export type ChangeOwnPasswordResponse = ChangeOwnPasswordResponses[keyof ChangeOwnPasswordResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        /**
         * 账号或显示名称的字面子串，不解释 SQL 通配符
         */
        search?: string;
        role?: 'user' | 'admin';
        enabled?: boolean;
    };
    url: '/api/users';
};

export type ListUsersErrors = {
    /**
     * 400 无效输入；401 登录失效；403 无管理权限；404 用户不存在；409 账号冲突/管理员保护；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    200: UserPage;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: CreateUserRequestWritable;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * 400 无效输入；401 登录失效；403 无管理权限；404 用户不存在；409 账号冲突/管理员保护；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    201: UserRecord;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type UpdateUserData = {
    body: UpdateUserRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * 400 无效输入；401 登录失效；403 无管理权限；404 用户不存在；409 账号冲突/管理员保护；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    200: UserRecord;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ResetUserPasswordData = {
    body: ResetPasswordRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/reset-password';
};

export type ResetUserPasswordErrors = {
    /**
     * 400 无效输入；401 登录失效；403 无管理权限；404 用户不存在；409 账号冲突/管理员保护；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type ResetUserPasswordError = ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
    204: void;
};

export type ResetUserPasswordResponse = ResetUserPasswordResponses[keyof ResetUserPasswordResponses];

export type ListManagementAuditData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        /**
         * 按审计记录 ID 精确查询，供详情路由直接加载
         */
        id?: number;
        /**
         * UTC ISO 8601 起始时间（含），须以 Z 结尾
         */
        from?: string;
        /**
         * UTC ISO 8601 结束时间（不含），须以 Z 结尾
         */
        to?: string;
        actor_user_id?: number;
        action?: string;
        success?: boolean;
    };
    url: '/api/audit';
};

export type ListManagementAuditErrors = {
    /**
     * 400 无效查询；401 登录失效；403 无管理权限；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type ListManagementAuditError = ListManagementAuditErrors[keyof ListManagementAuditErrors];

export type ListManagementAuditResponses = {
    200: AuditPage;
};

export type ListManagementAuditResponse = ListManagementAuditResponses[keyof ListManagementAuditResponses];
