// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type CenterInfo = {
    /**
     * 已实现能力；代理就绪后才声明 llm_proxy
     */
    capabilities: Array<string>;
    /**
     * Center 软件版本，与 Runtime 独立发布
     */
    software_version: string;
    /**
     * 当前企业协议版本
     */
    protocol_version: number;
    /**
     * 最低兼容企业协议版本
     */
    min_protocol_version: number;
};

export type CenterErrorDetail = {
    /**
     * 稳定原因码
     */
    code: string;
    /**
     * 脱敏错误说明
     */
    message: string;
    /**
     * 服务端生成的请求关联标识
     */
    request_id: string;
};

export type CenterErrorResponse = {
    error: CenterErrorDetail;
};

export type LoginRequest = {
    /**
     * 3—64 位 ASCII 账号，trim 后转小写
     */
    username: string;
};

export type IdentityUser = {
    id: number;
    username: string;
    display_name: string;
    role: 'user' | 'admin';
    is_super_admin: boolean;
    enabled: boolean;
};

export type LoginResponse = {
    center_id: string;
    user: IdentityUser;
    /**
     * 用于 Bearer 身份认证；仅内存保存，退出、撤销或中心重启后失效
     */
    token: string;
    /**
     * 仅供后续 LLM 代理使用，随本次 token 一起撤销；不用于身份 API
     */
    llm_key: string;
};

export type IdentityResponse = {
    center_id: string;
    user: IdentityUser;
};

export type PasswordRequest = {
    old_password: string;
    /**
     * 至少 6 位，包含英文字母和数字；不裁剪空白，最多 512 UTF-8 字节
     */
    new_password: string;
};

export type UserRecord = {
    id: number;
    username: string;
    display_name: string;
    role: 'user' | 'admin';
    is_super_admin: boolean;
    enabled: boolean;
    created_at: string;
    updated_at: string;
};

export type UserPage = {
    items: Array<UserRecord>;
    total: number;
    limit: number;
    offset: number;
};

export type CreateUserRequest = {
    /**
     * trim 并转小写后 3—64 位 ASCII 字母/数字及 ._-
     */
    username: string;
    display_name: string;
    role: 'user' | 'admin';
    enabled: boolean;
};

export type UpdateUserRequest = {
    display_name?: string;
    role?: 'user' | 'admin';
    enabled?: boolean;
};

export type ResetPasswordRequest = {
    /**
     * 至少 6 位，包含英文字母和数字；最多 512 UTF-8 字节；不收原密码，目标可为自己或超级管理员
     */
    new_password: string;
};

export type ModelSelection = {
    provider_instance_id: string;
    model_id: string;
};

export type AuditUserFields = {
    display_name?: string;
    role?: 'user' | 'admin';
    enabled?: boolean;
};

export type AuditDetails = {
    call_id?: string;
    side?: 'request' | 'response';
    enabled?: boolean;
    content_retention_days?: number;
    index_retention_days?: number;
    provider_instance_id?: string;
    model_id?: string;
    model_count?: number;
    count?: number;
    default_model?: ModelSelection | null;
    before?: AuditUserFields;
    after?: AuditUserFields;
};

export type AuditRecord = {
    id: number;
    occurred_at: string;
    actor_user_id: number | null;
    target_user_id: number | null;
    /**
     * 关联操作者的登录用户名；未认证或关联用户不存在时为空
     */
    actor_username: string | null;
    /**
     * 关联目标用户的登录用户名；无目标或关联用户不存在时为空
     */
    target_username: string | null;
    action: string;
    success: boolean;
    reason_code: string | null;
    request_id: string;
    details: AuditDetails;
};

export type AuditPage = {
    items: Array<AuditRecord>;
    total: number;
    limit: number;
    offset: number;
};

export type ProviderConnection = {
    display_name: string;
    provider_type: 'openai' | 'deepseek' | 'dashscope_api' | 'dashscope_plan' | 'moonshot' | 'zhipu' | 'vllm' | 'local';
    endpoint: string;
    protocol_preference: 'auto' | 'responses' | 'chat_completions';
    models_path: string;
    discovery_format: 'openai' | 'vllm' | 'moonshot' | 'dashscope_native';
};

export type ProviderSummary = {
    provider_instance_id: string;
    connection: ProviderConnection;
    has_api_key: boolean;
};

export type CredentialChange = {
    mode: 'unchanged' | 'replace' | 'clear';
};

export type SaveProvider = {
    connection: ProviderConnection;
    credential: CredentialChange;
};

export type ProviderUsage = {
    fixed_config_count: number;
    default_model: boolean;
};

export type ModelConfigurationSummary = {
    uses_template: boolean;
    requires_configuration: boolean;
};

export type TokenLimit = {
    state: 'unknown' | 'known' | 'invalid';
    value?: number;
};

export type ToolChoice = {
    auto: 'unknown' | 'supported' | 'unsupported';
    none: 'unknown' | 'supported' | 'unsupported';
    required: 'unknown' | 'supported' | 'unsupported';
    named: 'unknown' | 'supported' | 'unsupported';
};

export type ModelParameters = {
    context_window_tokens: TokenLimit;
    max_input_tokens: TokenLimit;
    max_output_tokens: TokenLimit;
    reasoning_max_input_tokens: TokenLimit;
    reasoning_max_output_tokens: TokenLimit;
    streaming: 'unknown' | 'supported' | 'unsupported';
    tool_choice: ToolChoice;
    tool_image_projection: 'unknown' | 'unsupported' | 'native_tool_result' | 'follow_up_user_message';
    image_input: 'unknown' | 'supported' | 'unsupported';
    tool_calls: 'unknown' | 'supported' | 'unsupported';
    reasoning: 'unknown' | 'supported' | 'unsupported';
    reasoning_mode: 'unknown' | 'unsupported' | 'optional' | 'always';
    reasoning_efforts: {
        [key: string]: string;
    } | null;
    default_reasoning_effort: 'low' | 'medium' | 'high' | 'xhigh' | 'max' | null;
};

export type CatalogModel = {
    configuration?: ModelConfigurationSummary;
    model_id: string;
    display_name: string | null;
    metadata: ModelParameters;
};

export type CatalogSnapshot = {
    provider_instance_id: string;
    models: Array<CatalogModel>;
    refreshed_at_ms: number | null;
    connection_changed: boolean;
};

export type ModelConfiguration = {
    provider_instance_id: string;
    model_id: string;
    origin: 'online' | 'manual';
    parameters: ModelParameters;
    source: 'fixed' | 'online' | 'template' | 'unconfigured';
    field_sources: {
        [key: string]: string;
    };
    updated_at_ms: number | null;
    template_document: string | null;
    template_checked_on: string | null;
    requires_configuration: boolean;
};

export type FixedConfigurationPage = {
    items: Array<ModelConfiguration>;
    total: number;
    offset: number;
    limit: number;
};

export type ModelConfigurationQuery = {
    provider_instance_id: string;
    model_id: string;
    origin: 'online' | 'manual';
};

export type SaveModelConfiguration = {
    provider_instance_id: string;
    model_id: string;
    origin: 'online' | 'manual';
    parameters: ModelParameters;
};

export type ModelSettings = {
    default_model: ModelSelection | null;
    state: 'ready' | 'unavailable';
    reason: string | null;
    configuration: ModelConfiguration | null;
};

export type SaveModelSettings = {
    default_model: ModelSelection | null;
};

export type TemplateStatus = {
    available: boolean;
    count: number;
    loaded_at_ms: number | null;
    error: string | null;
};

export type RuntimeModelConfiguration = {
    state: 'ready' | 'unavailable';
    center_id: string;
    reason?: string;
    endpoint?: string;
    provider_type?: 'openai' | 'deepseek' | 'dashscope_api' | 'dashscope_plan' | 'moonshot' | 'zhipu' | 'vllm' | 'local';
    provider_display_name?: string;
    protocol?: 'open_ai_responses' | 'open_ai_chat_completions';
    model_id?: string;
    parameters?: ModelParameters;
};

export type CallSnapshot = {
    state: 'disabled' | 'pending' | 'complete' | 'partial' | 'failed' | 'expired' | 'missing';
    bytes: number | null;
    sha256: string | null;
    reason: string | null;
};

export type CallDetails = {
    id: string;
    user_id: number | null;
    username: string | null;
    provider_instance_id: string | null;
    provider_name: string | null;
    model_id: string | null;
    kind: 'proxy' | 'admin_test';
    protocol: 'open_ai_responses' | 'open_ai_chat_completions';
    started_at: string;
    ended_at: string | null;
    http_status: number | null;
    reason: string | null;
    outcome: 'in_progress' | 'forwarded' | 'rejected' | 'upstream_error' | 'interrupted' | 'unknown';
    request: CallSnapshot;
    response: CallSnapshot;
};

export type CallPage = {
    items: Array<CallDetails>;
    total: number;
    limit: number;
    offset: number;
};

export type SnapshotContent = {
    state: 'disabled' | 'pending' | 'complete' | 'partial' | 'failed' | 'expired' | 'missing';
    bytes: number | null;
    sha256: string | null;
    reason: string | null;
    text: string | null;
};

export type RecordingSettings = {
    enabled: boolean;
    content_retention_days: number;
    index_retention_days: number;
};

export type TestModel = {
    provider_instance_id: string;
    model_id: string;
};

export type ModelTestResult = {
    call_id: string;
    http_status: number | null;
    connected: boolean;
    reason: string | null;
};

export type LoginRequestWritable = {
    /**
     * 3—64 位 ASCII 账号，trim 后转小写
     */
    username: string;
    password: string;
};

export type CreateUserRequestWritable = {
    /**
     * trim 并转小写后 3—64 位 ASCII 字母/数字及 ._-
     */
    username: string;
    display_name: string;
    role: 'user' | 'admin';
    enabled: boolean;
    /**
     * 至少 6 位，包含英文字母和数字；最多 512 UTF-8 字节
     */
    password: string;
};

export type CredentialChangeWritable = {
    mode: 'unchanged' | 'replace' | 'clear';
    value?: string;
};

export type SaveProviderWritable = {
    connection: ProviderConnection;
    credential: CredentialChangeWritable;
};

export type GetCenterInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/info';
};

export type GetCenterInfoErrors = {
    /**
     * 请求失败，返回脱敏原因码与请求标识
     */
    default: CenterErrorResponse;
};

export type GetCenterInfoError = GetCenterInfoErrors[keyof GetCenterInfoErrors];

export type GetCenterInfoResponses = {
    200: CenterInfo;
};

export type GetCenterInfoResponse = GetCenterInfoResponses[keyof GetCenterInfoResponses];

export type LoginData = {
    body: LoginRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * 400 输入无效；401 身份失败；403 来源/权限拒绝；409 状态变化；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type GetCurrentIdentityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentIdentityErrors = {
    /**
     * 400 输入无效；401 身份失败；403 来源/权限拒绝；409 状态变化；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type GetCurrentIdentityError = GetCurrentIdentityErrors[keyof GetCurrentIdentityErrors];

export type GetCurrentIdentityResponses = {
    200: IdentityResponse;
};

export type GetCurrentIdentityResponse = GetCurrentIdentityResponses[keyof GetCurrentIdentityResponses];

export type LogoutData = {
    body: {
        [key: string]: never;
    };
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * 400 输入无效；401 身份失败；403 来源/权限拒绝；409 状态变化；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ChangeOwnPasswordData = {
    body: PasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/password';
};

export type ChangeOwnPasswordErrors = {
    /**
     * 400 输入无效；401 身份失败；403 来源/权限拒绝；409 状态变化；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type ChangeOwnPasswordError = ChangeOwnPasswordErrors[keyof ChangeOwnPasswordErrors];

export type ChangeOwnPasswordResponses = {
    204: void;
};

export type ChangeOwnPasswordResponse = ChangeOwnPasswordResponses[keyof ChangeOwnPasswordResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        /**
         * 账号或显示名称的字面子串，不解释 SQL 通配符
         */
        search?: string;
        role?: 'user' | 'admin';
        enabled?: boolean;
    };
    url: '/api/users';
};

export type ListUsersErrors = {
    /**
     * 400 无效输入；401 登录失效；403 无管理权限；404 用户不存在；409 账号冲突/管理员保护；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    200: UserPage;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: CreateUserRequestWritable;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * 400 无效输入；401 登录失效；403 无管理权限；404 用户不存在；409 账号冲突/管理员保护；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    201: UserRecord;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type UpdateUserData = {
    body: UpdateUserRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * 400 无效输入；401 登录失效；403 无管理权限；404 用户不存在；409 账号冲突/管理员保护；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    200: UserRecord;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ResetUserPasswordData = {
    body: ResetPasswordRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/reset-password';
};

export type ResetUserPasswordErrors = {
    /**
     * 400 无效输入；401 登录失效；403 无管理权限；404 用户不存在；409 账号冲突/管理员保护；429 限流；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type ResetUserPasswordError = ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
    204: void;
};

export type ResetUserPasswordResponse = ResetUserPasswordResponses[keyof ResetUserPasswordResponses];

export type ListManagementAuditData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        /**
         * 按审计记录 ID 精确查询，供详情路由直接加载
         */
        id?: number;
        /**
         * UTC ISO 8601 起始时间（含），须以 Z 结尾
         */
        from?: string;
        /**
         * UTC ISO 8601 结束时间（不含），须以 Z 结尾
         */
        to?: string;
        actor_user_id?: number;
        action?: string;
        success?: boolean;
    };
    url: '/api/audit';
};

export type ListManagementAuditErrors = {
    /**
     * 400 无效查询；401 登录失效；403 无管理权限；503 服务不可用
     */
    default: CenterErrorResponse;
};

export type ListManagementAuditError = ListManagementAuditErrors[keyof ListManagementAuditErrors];

export type ListManagementAuditResponses = {
    200: AuditPage;
};

export type ListManagementAuditResponse = ListManagementAuditResponses[keyof ListManagementAuditResponses];

export type ListModelProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/model-providers';
};

export type ListModelProvidersErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type ListModelProvidersError = ListModelProvidersErrors[keyof ListModelProvidersErrors];

export type ListModelProvidersResponses = {
    200: Array<ProviderSummary>;
};

export type ListModelProvidersResponse = ListModelProvidersResponses[keyof ListModelProvidersResponses];

export type CreateModelProviderData = {
    body: SaveProviderWritable;
    path?: never;
    query?: never;
    url: '/api/model-providers';
};

export type CreateModelProviderErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type CreateModelProviderError = CreateModelProviderErrors[keyof CreateModelProviderErrors];

export type CreateModelProviderResponses = {
    201: ProviderSummary;
};

export type CreateModelProviderResponse = CreateModelProviderResponses[keyof CreateModelProviderResponses];

export type DeleteModelProviderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/model-providers/{id}';
};

export type DeleteModelProviderErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type DeleteModelProviderError = DeleteModelProviderErrors[keyof DeleteModelProviderErrors];

export type DeleteModelProviderResponses = {
    200: ProviderUsage;
};

export type DeleteModelProviderResponse = DeleteModelProviderResponses[keyof DeleteModelProviderResponses];

export type GetModelProviderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/model-providers/{id}';
};

export type GetModelProviderErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type GetModelProviderError = GetModelProviderErrors[keyof GetModelProviderErrors];

export type GetModelProviderResponses = {
    200: ProviderSummary;
};

export type GetModelProviderResponse = GetModelProviderResponses[keyof GetModelProviderResponses];

export type UpdateModelProviderData = {
    body: SaveProviderWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/model-providers/{id}';
};

export type UpdateModelProviderErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type UpdateModelProviderError = UpdateModelProviderErrors[keyof UpdateModelProviderErrors];

export type UpdateModelProviderResponses = {
    200: ProviderSummary;
};

export type UpdateModelProviderResponse = UpdateModelProviderResponses[keyof UpdateModelProviderResponses];

export type GetModelProviderUsageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/model-providers/{id}/usage';
};

export type GetModelProviderUsageErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type GetModelProviderUsageError = GetModelProviderUsageErrors[keyof GetModelProviderUsageErrors];

export type GetModelProviderUsageResponses = {
    200: ProviderUsage;
};

export type GetModelProviderUsageResponse = GetModelProviderUsageResponses[keyof GetModelProviderUsageResponses];

export type GetModelCatalogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/model-providers/{id}/catalog';
};

export type GetModelCatalogErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type GetModelCatalogError = GetModelCatalogErrors[keyof GetModelCatalogErrors];

export type GetModelCatalogResponses = {
    200: CatalogSnapshot;
};

export type GetModelCatalogResponse = GetModelCatalogResponses[keyof GetModelCatalogResponses];

export type RefreshModelCatalogData = {
    body: {
        [key: string]: never;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/model-providers/{id}/refresh';
};

export type RefreshModelCatalogErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type RefreshModelCatalogError = RefreshModelCatalogErrors[keyof RefreshModelCatalogErrors];

export type RefreshModelCatalogResponses = {
    200: CatalogSnapshot;
};

export type RefreshModelCatalogResponse = RefreshModelCatalogResponses[keyof RefreshModelCatalogResponses];

export type ListFixedModelConfigurationsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        offset?: number;
        limit?: number;
    };
    url: '/api/model-providers/{id}/fixed-configs';
};

export type ListFixedModelConfigurationsErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type ListFixedModelConfigurationsError = ListFixedModelConfigurationsErrors[keyof ListFixedModelConfigurationsErrors];

export type ListFixedModelConfigurationsResponses = {
    200: FixedConfigurationPage;
};

export type ListFixedModelConfigurationsResponse = ListFixedModelConfigurationsResponses[keyof ListFixedModelConfigurationsResponses];

export type QueryModelConfigurationData = {
    body: ModelConfigurationQuery;
    path?: never;
    query?: never;
    url: '/api/model-configuration/query';
};

export type QueryModelConfigurationErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type QueryModelConfigurationError = QueryModelConfigurationErrors[keyof QueryModelConfigurationErrors];

export type QueryModelConfigurationResponses = {
    200: ModelConfiguration;
};

export type QueryModelConfigurationResponse = QueryModelConfigurationResponses[keyof QueryModelConfigurationResponses];

export type SaveModelConfigurationData = {
    body: SaveModelConfiguration;
    path?: never;
    query?: never;
    url: '/api/model-configuration';
};

export type SaveModelConfigurationErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type SaveModelConfigurationError = SaveModelConfigurationErrors[keyof SaveModelConfigurationErrors];

export type SaveModelConfigurationResponses = {
    200: ModelConfiguration;
};

export type SaveModelConfigurationResponse = SaveModelConfigurationResponses[keyof SaveModelConfigurationResponses];

export type ResetModelConfigurationData = {
    body: ModelSelection;
    path?: never;
    query?: never;
    url: '/api/model-configuration/reset';
};

export type ResetModelConfigurationErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type ResetModelConfigurationError = ResetModelConfigurationErrors[keyof ResetModelConfigurationErrors];

export type ResetModelConfigurationResponses = {
    204: void;
};

export type ResetModelConfigurationResponse = ResetModelConfigurationResponses[keyof ResetModelConfigurationResponses];

export type GetModelSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/model-settings';
};

export type GetModelSettingsErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type GetModelSettingsError = GetModelSettingsErrors[keyof GetModelSettingsErrors];

export type GetModelSettingsResponses = {
    200: ModelSettings;
};

export type GetModelSettingsResponse = GetModelSettingsResponses[keyof GetModelSettingsResponses];

export type SaveModelSettingsData = {
    body: SaveModelSettings;
    path?: never;
    query?: never;
    url: '/api/model-settings';
};

export type SaveModelSettingsErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type SaveModelSettingsError = SaveModelSettingsErrors[keyof SaveModelSettingsErrors];

export type SaveModelSettingsResponses = {
    200: ModelSettings;
};

export type SaveModelSettingsResponse = SaveModelSettingsResponses[keyof SaveModelSettingsResponses];

export type GetModelTemplateStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/model-templates';
};

export type GetModelTemplateStatusErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type GetModelTemplateStatusError = GetModelTemplateStatusErrors[keyof GetModelTemplateStatusErrors];

export type GetModelTemplateStatusResponses = {
    200: TemplateStatus;
};

export type GetModelTemplateStatusResponse = GetModelTemplateStatusResponses[keyof GetModelTemplateStatusResponses];

export type ReloadModelTemplatesData = {
    body: {
        [key: string]: never;
    };
    path?: never;
    query?: never;
    url: '/api/model-templates/reload';
};

export type ReloadModelTemplatesErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type ReloadModelTemplatesError = ReloadModelTemplatesErrors[keyof ReloadModelTemplatesErrors];

export type ReloadModelTemplatesResponses = {
    200: TemplateStatus;
};

export type ReloadModelTemplatesResponse = ReloadModelTemplatesResponses[keyof ReloadModelTemplatesResponses];

export type GetRuntimeModelConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/runtime/model-configuration';
};

export type GetRuntimeModelConfigurationErrors = {
    /**
     * 身份、参数、配置冲突或服务失败；不返回凭据与上游正文
     */
    default: CenterErrorResponse;
};

export type GetRuntimeModelConfigurationError = GetRuntimeModelConfigurationErrors[keyof GetRuntimeModelConfigurationErrors];

export type GetRuntimeModelConfigurationResponses = {
    200: RuntimeModelConfiguration;
};

export type GetRuntimeModelConfigurationResponse = GetRuntimeModelConfigurationResponses[keyof GetRuntimeModelConfigurationResponses];

export type ListLlmCallsData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        user_id?: number;
        provider_instance_id?: string;
        model_id?: string;
        outcome?: string;
        kind?: string;
        from?: string;
        to?: string;
        limit?: number;
        offset?: number;
    };
    url: '/api/llm-calls';
};

export type ListLlmCallsErrors = {
    /**
     * 身份、参数或存储失败
     */
    default: CenterErrorResponse;
};

export type ListLlmCallsError = ListLlmCallsErrors[keyof ListLlmCallsErrors];

export type ListLlmCallsResponses = {
    200: CallPage;
};

export type ListLlmCallsResponse = ListLlmCallsResponses[keyof ListLlmCallsResponses];

export type GetLlmCallData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/llm-calls/{id}';
};

export type GetLlmCallErrors = {
    /**
     * 身份、参数或存储失败
     */
    default: CenterErrorResponse;
};

export type GetLlmCallError = GetLlmCallErrors[keyof GetLlmCallErrors];

export type GetLlmCallResponses = {
    200: CallDetails;
};

export type GetLlmCallResponse = GetLlmCallResponses[keyof GetLlmCallResponses];

export type GetLlmSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        side: 'request' | 'response';
    };
    url: '/api/llm-calls/{id}/snapshot';
};

export type GetLlmSnapshotErrors = {
    /**
     * 身份、参数或存储失败
     */
    default: CenterErrorResponse;
};

export type GetLlmSnapshotError = GetLlmSnapshotErrors[keyof GetLlmSnapshotErrors];

export type GetLlmSnapshotResponses = {
    200: SnapshotContent;
};

export type GetLlmSnapshotResponse = GetLlmSnapshotResponses[keyof GetLlmSnapshotResponses];

export type GetLlmRecordingSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/llm-recording-settings';
};

export type GetLlmRecordingSettingsErrors = {
    /**
     * 身份、参数或存储失败
     */
    default: CenterErrorResponse;
};

export type GetLlmRecordingSettingsError = GetLlmRecordingSettingsErrors[keyof GetLlmRecordingSettingsErrors];

export type GetLlmRecordingSettingsResponses = {
    200: RecordingSettings;
};

export type GetLlmRecordingSettingsResponse = GetLlmRecordingSettingsResponses[keyof GetLlmRecordingSettingsResponses];

export type SaveLlmRecordingSettingsData = {
    body: RecordingSettings;
    path?: never;
    query?: never;
    url: '/api/llm-recording-settings';
};

export type SaveLlmRecordingSettingsErrors = {
    /**
     * 身份、参数或存储失败
     */
    default: CenterErrorResponse;
};

export type SaveLlmRecordingSettingsError = SaveLlmRecordingSettingsErrors[keyof SaveLlmRecordingSettingsErrors];

export type SaveLlmRecordingSettingsResponses = {
    200: RecordingSettings;
};

export type SaveLlmRecordingSettingsResponse = SaveLlmRecordingSettingsResponses[keyof SaveLlmRecordingSettingsResponses];

export type TestModelConfigurationData = {
    body: TestModel;
    path?: never;
    query?: never;
    url: '/api/model-configuration/test';
};

export type TestModelConfigurationErrors = {
    /**
     * 身份、参数或存储失败
     */
    default: CenterErrorResponse;
};

export type TestModelConfigurationError = TestModelConfigurationErrors[keyof TestModelConfigurationErrors];

export type TestModelConfigurationResponses = {
    200: ModelTestResult;
};

export type TestModelConfigurationResponse = TestModelConfigurationResponses[keyof TestModelConfigurationResponses];
